//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chronos
{
    using System;
    using System.Collections.Generic;
    
    public partial class EquipamentoHardware
    {
        public int Id { get; set; }
        public int IdEquipamento { get; set; }
        public string Processador { get; set; }
        public string Placa_mae { get; set; }
        public string Memoria { get; set; }
        public string SO { get; set; }
        public string Video { get; set; }
        public string Som { get; set; }
        public int NumSerie { get; set; }
        public int Codigo { get; set; }
    }
}
