//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chronos
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoginCliente
    {
        public int Id { get; set; }
        public int IdPerfil { get; set; }
        public string Login { get; set; }
        public int IdCliente { get; set; }
        public string Senha { get; set; }
        public bool Ativo { get; set; }
    }
}
