//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chronos
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdemServico
    {
        public int Id { get; set; }
        public int Codigo { get; set; }
        public int IdServico { get; set; }
        public int IdCliente { get; set; }
        public string Diagnostico { get; set; }
        public string Status { get; set; }
        public int idFuncionario { get; set; }
        public string Realizado { get; set; }
        public int IdGarantia { get; set; }
        public System.DateTime Entrada { get; set; }
        public System.DateTime Saida { get; set; }
        public decimal Total { get; set; }
        public string Defeito { get; set; }
        public int IdPeca { get; set; }
        public int IdEquipamento { get; set; }
    }
}
