//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chronos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Servico
    {
        public int Id { get; set; }
        public int Codigo { get; set; }
        public string Servico1 { get; set; }
        public decimal Valor { get; set; }
    }
}
